server:
  port: 9098

spring:
  application:
    name: c-talk
  data:
    mongodb:
      username: cgy
      password: cgy123456
      host: 192.168.85.51
      port: 27017
      database: c_talk

eureka:
  instance:
    hostname: 10.0.0.37
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.0.37:9099/eureka/
feign:
  client:
    config:
      default:
        connect-timeout: 2000
        readTimeout: 60000
